### ISSUE TITLE
Doesn't work correctly in IE8 and IE9

### ISSUE THREAD

**Issue by edge0703** [10up/flexibility#11]
Just made a pen to see how the script works, but unfortunately it neither works correctly in IE8 nor IE9:
http://s.codepen.io/edge0703/debug/pgbBaQ

In IE8 the elements are distributed across the page, but there's no spacing between the elements, as it would normally be with justify-content: space-between. In IE9 flexbox is ignored at all and everything is displayed as if flexbox wouldn't be present.

**Comment by retlehs** [comment]
your pen is trying to load the flexibility JS directly from raw github and it's being blocked:

```
Refused to execute script from 'https://raw.githubusercontent.com/10up/flexibility/master/dist/flexibility.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

use https://rawgit.com/ instead

**Comment by QWp6t** [comment]
User error.

> Refused to execute script from 'https://raw.githubusercontent.com/10up/flexibility/master/dist/flexibility.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Don't load directly from raw.githubusercontent.com.

**Comment by edge0703** [comment]
Ah, sorry, my fault. Changed the script to the correct path now, but it still doesn't work correctly. If you compare the output in a modern browser like Chrome to IE8 oder IE9 then you see that "justify-content: space-between" for example doesn't distribute the 3 elements across the screen with even gaps between, but shoves everything to the left side of the screen with very little (IE9) to no spacing (IE8) in between.

Chrome:
![image](https://cloud.githubusercontent.com/assets/2077473/12014465/7879f484-ad2d-11e5-8c85-0c6d1d144d94.png)

IE8:
![image](https://cloud.githubusercontent.com/assets/2077473/12014470/a294a732-ad2d-11e5-9c8d-f8bd60e4864f.png)

IE9:
![image](https://cloud.githubusercontent.com/assets/2077473/12014474/bb309256-ad2d-11e5-8282-13bc644c0473.png)

Used real IEs on Browserstack to test it.

**Comment by jonathantneal** [comment]
Not all of the flexbox feature set has been ported. I’ve recently added a few major bug fixes, but I am really hoping another developer (or developers) will join me in mapping out the complete flexbox feature set.

**Comment by jonathantneal** [comment]
Matching the viewport is complicated in IE8 and I’m still looking into this. However, the premise of this has been accounted for and the ability to do this has been added to Flexibility. See [test-widths.html](https://github.com/10up/flexibility/blob/master/tests/test-widths.html) and let me know if you feel this gives you the functionality you were expecting.

**Comment by edge0703** [comment]
When I open my link it seems to work now, thanks. 

But one strange thing: You have the test page (https://10up.github.io/flexibility/) in your repository, but it don't even works in IE9. When I open the page there the dropdowns don't work at all, so what's the sense of all of that? It's great that I can play around in Chrome with it, but for me the deal would be to use it as a test page in oldIE.

Don't get the wrong impression, I really don't want to blame you, just help to make your script more useful.

**Comment by jonathantneal** [comment]
I will continue working to support stretched columns matching the height of the viewport.

A little background: Flexbox calculations are handled by Facebook’s [css-layout](https://github.com/facebook/css-layout). I parse and calculate all of the keywords and lengths from IE8 & IE9 to feed it. Additionally, I shim support for `order` and `flex-flow`. css-layout mislabeled `flex-grow` support as `flex` support, but I am now correcting this within Flexibility, so we have partial support. I’ve added tests for all of these as well.

Thank you for finding the IE9 bug on the demo page. An update caused IE9 to stop responding to changes in the select dropdown, but this has been resolved. I made the mistake of only testing IE8, forgetting that IE9 is a very different beast.

May we narrow this issue down to equal height columns matching the span of the whole page. Then, once I can resolve that and provide a test, I would like to close this issue.

**Comment by jonathantneal** [comment]
Good news, Flexibility is now handling `flex-grow`, and your [pen](http://s.codepen.io/edge0703/debug/bEYGMW) is working and tested in IE8 & IE9 as of Flexibility v1.0.6.

**Comment by edge0703** [comment]
Great work, everything in my pen works as expected now. 

I just noticed one thing on the test page: "flex-wrap" doesn't seem to work in IE9, as I don't see a change when I swap from "wrap" to "nowrap".

If flexbility.js would support "flexing" (flex: 1 for example) now it would be perfect.

**Comment by gadzhimari** [comment]
Hi, Jonathan. I don't know what I'm doing wrong, but nothing doesn't helped me. I include in gulpfile postcss plugin which automate add js prefixes in css file. But now I tested site prototype in ie8 through Virtual Machine, and nothing at all working. 
![2016-11-30_11-43-28](https://cloud.githubusercontent.com/assets/1849608/20745407/4c15b32c-b6f2-11e6-8ae4-f2fe6e924772.png)
Here the compiled source
[site.zip](https://github.com/jonathantneal/flexibility/files/621288/site.zip)
