### ISSUE TITLE
IE9 and justify-content:center

### ISSUE THREAD

**Issue by benweiser** [10up/flexibility#15]
Tested in IE 9.0.8xxx on a Windows 7 machine, the polyfill is used with justify-content:center and align-items:center on a single flex item. It appears to be centering vertically but not horizontally. 

See codepen below,

http://codepen.io/benweiser/pen/qbRWjZ
http://codepen.io/benweiser/live/qbRWjZ

**Comment by jonathantneal** [comment]
Good news, this has been resolved in Flexbox v1! This specific URL has been tested in IE8 and IE9, and a [similar test](https://github.com/10up/flexibility/blob/master/tests/test-centering.html) has been added to this repo.

**Comment by dottodot** [comment]
Can you explain what the solution is. I'm using v1.0.6 and my content isn't aligned in the center when I use

```
.home-top, .home-bottom {
  -js-display: flex;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
    .home-widget {
        flex-direction: column;
        justify-content: center;
        align-items: center;
  }
}
```
