### ISSUE TITLE
Is flexibility.js fix IE 11 min height issue?

### ISSUE THREAD

**Issue by maheshwaghmare** [10up/flexibility#16]
As we know IE 11 does not vertically align items correctly when min-height is used. [See bug](https://connect.microsoft.com/IE/feedback/details/816293/ie11-flexbox-with-min-height-not-vertically-aligning-with-align-items-center)

Is flexibility.js fix this issue?

**Comment by jonathantneal** [comment]
No, this would be out of scope for this project. However, there is another project devoted to flexbox workarounds. Checkout https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items
