### ISSUE TITLE
Missing support for "justify-content: space-between;"

### ISSUE THREAD

**Issue by konrad-ha** [10up/flexibility#18]
Let me start off with saying that this is fantastic. A polyfill for flexbox is what is missing to make my life complete (as a webdev).

I just wanted to add this here so it doesn't get forgotten: "justify-content: space-between;" would be nice, it does wonders for some layouts.

**Comment by jonathantneal** [comment]
This has now been added in Flexibility v1! Thank you so much for your kind words. It means a lot when you know this could really help people and so you’re coding and coding and suddenly it’s 3am. So it’s really great to read that someone appreciates what we do.
