### ISSUE TITLE
project closed? (not working in ie 8, ie 9)

### ISSUE THREAD

**Issue by anorudes** [10up/flexibility#20]
The library doesn't work on real ie 8, 9. I see that all new commits edit rows in readme.md but not have  fix any bug

**Comment by jonathantneal** [comment]
The rumors of my death have been greatly exaggerated.

Nearly every pull request has been to edit the `README.md` or `package.json`. I am presently making changes to the code.

![Diagram of Developers](https://cloud.githubusercontent.com/assets/188426/12208662/2d12a818-b61c-11e5-98dc-710a5b434a6a.png)

Valid tests are welcome, as is reading [CONTRIBUTING.md](https://github.com/10up/flexibility/blob/master/CONTRIBUTING.md). How might you help?

*goes back to [coding](http://jonneal.bandcamp.com/track/codin)*
