### ISSUE TITLE
does flexibility support android old versions

### ISSUE THREAD

**Issue by tlightsky** [10up/flexibility#22]
does flexibility support android old versions
such as android 4.1,4.2

**Comment by Nitrino** [comment]
Android 4.0+ supported autoprefixer if the flag is set Android > = 4

**Comment by tlightsky** [comment]
@Nitrino It seems only support flexbox 2009 not flexbox 2012
maybe I forget to set flag in some where?

**Comment by Nitrino** [comment]
@tlightsky Between these standards in practice not much difference if you use autoprefixer. I try not to use multi-line flexbox and everything works, only in rare places slightly different behavior.

**Comment by Nitrino** [comment]
My settings autoprefixer `{browsers: ['last 2 versions', 'ie 9', 'ie 10', 'Android >= 4']}`

**Comment by jonathantneal** [comment]
Yes, please use [Autoprefixer](https://github.com/postcss/autoprefixer) to support Flexbox 2009 compatible browsers.
