### ISSUE TITLE
IE8: Invalid Argument

### ISSUE THREAD

**Issue by zovt** [10up/flexibility#23]
Seem to be getting this error in IE8:

Invalid Argument
Line: 2
Char: 1083

Not sure what's causing it. I've replaced all instances of

```
display: flex;
```

with

```
-js-display: flex;
display: block;
display: flex;
```

Am I misunderstanding something?

**Comment by jonathantneal** [comment]
You are doing it right. Would you try Flexibility v1 and tell me if you still get this error?

**Comment by jonathantneal** [comment]
We have a demo page tested on IE8 and IE9 with no errors. http://10up.github.io/flexibility/

If you can provide a test case in Flexibility v1, I’ll be happy to look into it.
