### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by nickcolley** [10up/flexibility#43]
I was thinking of using this for iOS since I've got a bug that I can't workaround, is that possible?

**Comment by Dan503** [comment]
iOS supports flexbox. This is only for making flexbox work in IE 8 & 9 since flexbox doesn't work in either of those at all.

**Comment by OctoD** [comment]
https://github.com/philipwalton/flexbugs Try reading this guide, maybe you will find the correct answer to your problem.

**Comment by nickcolley** [comment]
Flexbox works for the majority of cases but I have a specific usecase not defined in flexbugs involving min-widths not wrapping correctly.

So I'm just wondering what it'd take to run this on iOS to fix the incorrect behaviour?

**Comment by Dan503** [comment]
This issue is a bit like asking for a screwdriver to be given the ability to hammer nails. It's not what the tool is for.

**Comment by nickcolley** [comment]
Considering the React team are considering implementing layout into the framework itself I don't think proposing to override the default renderer in iOS is so outlandish.

Would I need to building something from scratch with css-layout? I'm just trying to determine if this is only an IE library or not.
