### ISSUE TITLE
Do this polyfill even work anymore?

### ISSUE THREAD

**Issue by PayteR** [10up/flexibility#45]
Hi, i'm trying to make this work on my IE8/9 but it's not work at all. It's not working in my project and even in test page https://10up.github.io/flexibility/. Throught browserstack is same result, whats wrong?

![2016-03-22_2107](https://cloud.githubusercontent.com/assets/1248565/13966662/c9ee2d42-f073-11e5-9352-0dd5ebbd48b3.png)

**Comment by julian-goldsmith** [comment]
In my experience it works with IETester, but not IE11.  It seems that the detection is broken for IE11, since it does work if you manually run flexibility.walk in the console.

**Comment by PayteR** [comment]
I downloaded IE tester on my W10 machine, but exactly tabs IE8 and IE9 did not work. So i tried it on W7 machine, tabs worked, but its not my dev machine, so i'm not able to test my work on my dev machine. Best would be to fix browser detection on IE11 compatibility mode, could you do that please?

and flexibility.walk() did not work 
![2016-03-23_1309](https://cloud.githubusercontent.com/assets/1248565/13984785/bc068aaa-f0f8-11e5-9267-4737daa65bff.png)

**Comment by julian-goldsmith** [comment]
You'd want to call flexibility.walk a bit differently.  Call it like: flexibility.walk(document.getElementById('demo')) .
