### ISSUE TITLE
css-layout.js and other files

### ISSUE THREAD

**Issue by BMCwebdev** [10up/flexibility#47]
Currently I have only the flexibility.js script called for in my page. However, upon reading the support section, it looks like perhaps there are other scripts that are needed to get Flexibility to fully work? Files such as css-layout.js. Is this the case, do I need all the dependencies?

**Comment by marvinhagemeister** [comment]
No, you only need the `flexbility.js` from the `dist` folder. The distribution version includes all other js files

**Comment by jonathantneal** [comment]
@marvinhagemeister is correct. I may move the final file in `dist` to the root, to avoid confusion in the future. This is similar to what I do in sanitize.css and normalize.css.
