### ISSUE TITLE
Using --js-display rather than -js-display?

### ISSUE THREAD

**Issue by fvsch** [10up/flexibility#6]
Just a thought. Would it be feasible and relevant to use the cascading variables syntax, aka `--js-display`, rather than a kind-of-vendor-prefix?

Technical difficulties I can think of:

1. If IE 8 and/or 9 discards properties starting with (or containing) `--` and the script cannot detect them, that's a no-go.
2. Some *-to-CSS processors may treat cascading variables as static variables and strip them.

**Comment by jonathantneal** [comment]
@fvsch, thanks for checking out the project. That’s a wonderful thought, and I had not considered it.

Unfortunately, I did some testing in IE just now, and it fails to read properties beginning with a double-dash.
