### ISSUE TITLE
IE9,IE10 no support

### ISSUE THREAD

**Issue by zhouwenbin** [10up/flexibility#7]
IE9,IE10 no support,noly support IE8

**Comment by jonathantneal** [comment]
Thanks for reaching out to me. I think you may have encountered an error with text nodes in IE9. Would you get the latest and tell me if the demos are working for you?

**Comment by zhouwenbin** [comment]
in IE9，text display two lines.

**Comment by anorudes** [comment]
yes, it's not working. screenshot: https://monosnap.com/file/QHpOsfH04zvLCCFdS6kcUZ9QS7mOmy

**Comment by AdrianoCahete** [comment]
Native IE9/IE10 or emulated by IE11 (on Win 8.0) ?

**Comment by anorudes** [comment]
native and emulated

**Comment by exside** [comment]
maybe because of this? https://github.com/10up/flexibility/issues/3

**Comment by jawittdesigns** [comment]
Yeah, testing this with the demos in the package on browserstack yielded no results. It looks like the only property that actually works display:flex. Nothing else works. 

I think releasing this was a bit presumptuous.

**Comment by jonathantneal** [comment]
@zhouwenbin, IE10 has a [level of flexbox support](http://caniuse.com/#feat=flexbox) available through [Autoprefixer](https://github.com/postcss/autoprefixer). IE9 has an issue with whitespace related to #3 that I have just patched. I am presently building a release.

**Comment by jonathantneal** [comment]
Release ... released!

**Comment by jawittdesigns** [comment]
It still doesn't work. All the same issues.
