### ISSUE TITLE
JS exception: "Unable to get property 'boxSizing' of undefined or null reference"

### ISSUE THREAD

**Issue by mistakster** [10up/flexibility#8]
Hi!

I faced with the following issue. I'm getting JS error in console when the page contains inline SVG elements.

Link to test: https://jsfiddle.net/xL8fseze/5/embedded/result/

**Environment:** IE11 in "Document mode 9"

**Comment by jonathantneal** [comment]
This may be due to the current style not being accessible on those elements. In this case, I’ll provide an plain object fallback so this doesn’t choke the whole process.

**Comment by jonathantneal** [comment]
This has now been pushed into 0.3.0! Thanks for spotting this, @mistakster!

**Comment by mistakster** [comment]
Cool. Thank you!
