### ISSUE TITLE
Look into reusing css-layout if possible ? 

### ISSUE THREAD

**Issue by ganarajpr** [10up/flexibility#9]
I am not sure if this has been looked into already or not.. But I thought a possible discussion about possibly re-using facebooks css-layout would be a good idea at this stage in the project. 

https://github.com/facebook/css-layout

They already have a pretty stable implementation as far as I can tell - and is being used in react-native for rendering. 

The main difference I can see is that - the flexibility.transform seems to be using margins while the css-layout provides absolute positions for all nodes.

**Comment by jonathantneal** [comment]
I’m definitely open to this if someone can make the pull.

**Comment by jonathantneal** [comment]
Never the less, I’m willing to look into it. Thanks for pointing me to this, @ganarajpr. https://github.com/10up/flexibility/tree/css-layout
